name: 'action-config'
description: 'Github Action for reading configuration files and generating workflow matrices'
author: 'group:default/dai'

inputs:
  config_path:
    description: 'Path to the configuration file (JSON or YAML)'
    required: true
    default: '.github/matrix-config.json'
  dimension_key:
    description: 'Override the dimension_key from config. Switches the primary dimension and removes the config dimension from the matrix.'
    required: false
    default: ''
  target:
    description: 'Filter by dimension_key value(s). Comma-separated for multiple (e.g. "api,frontend"). If a single value matches a dimension name (not a value of the current dimension_key), it switches the primary dimension instead.'
    required: false
    default: ''
  environment:
    description: 'Filter environments. Comma-separated for multiple (e.g. "dev,prod")'
    required: false
    default: ''
  exclude:
    description: 'JSON array of patterns to exclude from the matrix (e.g. [{"service":"shared","environment":"dev"}])'
    required: false
    default: ''
  include:
    description: 'JSON array of entries to append to the matrix (e.g. [{"service":"shared"}])'
    required: false
    default: ''
  change_detection:
    description: 'When true, use git to detect changed files and filter the matrix to only entries with changes. Uses base_dir from global to map file paths. Requires actions/checkout with fetch-depth: 0.'
    required: false
    default: 'false'

outputs:
  matrix:
    description: 'JSON string containing the matrix configuration'
  changes_detected:
    description: 'Whether any entries have changes (true/false). Only meaningful when change_detection is true.'
  config:
    description: 'JSON object keyed by dimension values for direct field access via fromJson(). E.g. fromJson(steps.<id>.outputs.config).dev.api.directory'
  length:
    description: 'Number of entries in the matrix (e.g. "4"). Useful for conditional job execution: if: needs.setup.outputs.length > 0'
  # When the matrix contains exactly one entry, each of its fields is also emitted as a flat output.
  # E.g. steps.<id>.outputs.aws_region, steps.<id>.outputs.directory, etc.

runs:
  using: 'docker'
  image: 'docker://ghcr.io/dnd-it/action-config:2.1.0' # x-release-please-version

branding:
  icon: 'zap'
  color: 'blue'
